SaloSimulatorWeb2/Controllers/ConfigurationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Salo.SaloSimulatorWeb2.Models;
using System.Data.Entity;

namespace SaloSimulatorWeb2.Controllers
{
    public class ConfigurationController : Controller
    {
        //
        // GET: /Configuration/
        public ActionResult Index()
        {
            return View();
        }

        public new ActionResult View(string id = "default")
        {
            using (var context = new ApplicationDbContext())
            {
                return View(context.Configurations.Include(x => x.Parent).Include(x => x.Settings).SingleOrDefault(x => x.Name == id));
            }
        }
	}
}

SaloSimulatorWeb2/Views/Configuration/Index.cshtml
@model IEnumerable<Salo.Configuration>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Name }) |
            @Html.ActionLink("Details", "Details", new { id=item.Name }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Name })
        </td>
    </tr>
}

</table>

SaloSimulatorWeb2/Views/Configuration/View.cshtml
@model Salo.Configuration

@{
    ViewBag.Title = "View";
}

<div>
    <h2>@Model.Name <span style="color: #ccc"> :: @Html.ActionLink(Model.Parent == null ? "null" : Model.Parent.Name, "View", "Configuration")</span></h2>
    <hr />
    <table class="configuration-table">
        <tr>
            <th>Key</th>
            <th>Value</th>
            <th></th>
        </tr>
        @foreach (var kvp in Model.Settings)
        {
            <tr>
                <td>@kvp.Key</td>
                <td>@kvp.Value</td>
                <td><a href="https://github.com/ameerkat/Salo/search?q=ConfigurationKeys.@kvp.Key">Find Usages</a></td>
            </tr>
        }
    </table>
    <dl class="dl-horizontal">
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Name }) |
    @Html.ActionLink("Back to List", "Index")
</p>