SaloSimulatorWeb2/Models/Bot.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Salo.SaloSimulatorWeb2.Models
{
    public class Bot
    {
        [Key]
        public int Id { get; set; }

        public ApplicationUser Uploader { get; set; }
        public String BotName { get; set; }
        public String BotVersion { get; set; }
        public String BotDescription { get; set; }
        public String AssemblyPath { get; set; }
        public DateTime Created { get; set; }
    }
}

SaloSimulatorWeb2/Controllers/BotController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net.Mime;
using System.Reflection;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Salo;
using Salo.SaloSimulatorWeb2.Models;

namespace Salo.SaloSimulatorWeb2.Controllers
{
    public class BotController : Controller
    {
        public enum MessageType { Ok, Error }

        [Authorize]
        [HttpPost]
        public ActionResult Upload(HttpPostedFileBase file)
        {
            if (file.ContentLength > 0)
            {
                var fileName = Path.GetFileName(file.FileName);
                var folder = Server.MapPath("~/App_Data/Bots/tmp/");
                var path = Path.Combine(folder, Guid.NewGuid().ToString() + ".dll");
                System.IO.Directory.CreateDirectory(folder);
                file.SaveAs(path);
                // load up the info
                Assembly assembly;
                try
                {
                    assembly = Assembly.LoadFrom(path);
                }
                catch (Exception exception)
                {
                    ViewBag.Message = "Failed to load assembly.";
                    ViewBag.MessageType = MessageType.Error;
                    System.IO.File.Delete(path); // remove from temporary
                    return View("Create");
                }

                var types = assembly.GetExportedTypes();
                foreach (var type in types)
                {
                    if (type.IsClass)
                    {
                        var interfaces = type.GetInterfaces();
                        if (interfaces.Any(x => x == typeof (ISaloBot)))
                        {
                            var bot = new Bot();
                            bot.Created = DateTime.UtcNow;
                            var attributes = type.GetCustomAttributes(true);
                            var botName = (BotName) attributes.FirstOrDefault(a => a is BotName);
                            var botDescription = (BotDescription) attributes.FirstOrDefault(a => a is BotDescription);
                            if (botName != null)
                            {
                                bot.BotName = botName.Name;
                                bot.BotVersion = botName.Version;
                            }
                            else
                            {
                                // use class name as bot name
                                bot.BotName = type.Name;
                                // use assembly version for version info
                                var versionString =
                                    Regex.Match(assembly.FullName, @"Version=\s*(\d[\d\.]*)\s*,").Groups[1].Value;
                                bot.BotVersion = versionString;
                            }

                            if (botDescription != null)
                            {
                                bot.BotDescription = botDescription.Description;
                            }
                            else
                            {
                                // use no description
                                bot.BotDescription = String.Empty;
                            }

                            var newFolder =
                                Server.MapPath(String.Format("~/App_Data/Bots/{0}/{1}/{2}", this.User.Identity.Name,
                                    bot.BotName, bot.BotVersion));
                            var newPath = Path.Combine(newFolder, fileName);
                            bot.AssemblyPath = newPath;
                            System.IO.Directory.CreateDirectory(newFolder);
                            file.SaveAs(newPath);

                            using (var appContext = new ApplicationDbContext())
                            {
                                var existingBot =
                                    appContext.Bots.FirstOrDefault(
                                        x => x.BotName == bot.BotName && x.BotVersion == bot.BotVersion);
                                if (existingBot != null)
                                {
                                    bot.Id = existingBot.Id;
                                }

                                bot.Uploader = appContext.Users.Find(this.User.Identity.GetUserId());
                                appContext.Bots.Add(bot);
                                try
                                {
                                    appContext.SaveChanges();
                                }
                                catch (DbEntityValidationException ex)
                                {
                                    throw;
                                }
                            }
                        }
                    }
                }
                return RedirectToAction("Index");
            }

            ViewBag.Message = "No file attached...";
            ViewBag.MessageType = MessageType.Error;
            return View("Create");
        }

        //
        // GET: /Bot/
        public ActionResult Index()
        {
            List<Bot> bots;
            using (var botContext = new ApplicationDbContext())
            {
                bots = botContext.Bots.Include(x => x.Uploader).ToList();
            }
            return View(bots);
        }

        public ActionResult Create()
        {
            return View();
        }
	}
}

SaloSimulatorWeb2/Views/Bot/Create.cshtml
@model Salo.SaloSimulatorWeb2.Models.Bot

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@if (ViewBag.Message != null)
{
    <p>@ViewBag.Message</p>
}

@using (Html.BeginForm("Upload", "Bot", FormMethod.Post, new Dictionary<string, object>(){ {"enctype", "multipart/form-data" }})) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Bot</h4>
        <hr />
        @Html.ValidationSummary(true)

        <label for="file">Assembly: </label>
        <input type="file" name="file" id="file" />

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SaloSimulatorWeb2/Views/Bot/Index.cshtml
@model IEnumerable<Salo.SaloSimulatorWeb2.Models.Bot>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@if (ViewBag.Message != null)
{
    <p>@ViewBag.Message</p>
}

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.BotName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BotVersion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BotDescription)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AssemblyPath)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Created)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.BotName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BotVersion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BotDescription)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AssemblyPath)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Created)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>